---
- name: create node exporter group
  group:
    name: "{{ node_exporter_group }}"
    state: present
    system: true

- name: create node exporter user
  user:
    name: "{{ node_exporter_user }}"
    groups: "{{ node_exporter_group }}"
    append: true
    shell: /bin/bash
    create_home: false

- name: check if node exporter version already exists
  stat:
    path: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64"
  register: prometheus_node_exporter_install_path

- name: download node exporter
  get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
  when: not prometheus_node_exporter_install_path.stat.exists

- name: extract node exporter into the install directory
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    dest: "/opt/"
    copy: false
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
  when: not prometheus_node_exporter_install_path.stat.exists

- name: create a symlink for /opt/node_exporter
  file:
    src: "/opt/node_exporter-{{ node_exporter_version }}.linux-amd64"
    dest: /opt/node_exporter
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    state: link
  when: not prometheus_node_exporter_install_path.stat.exists

- name: copy node exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart node_exporter

- name: ensure node exporter is started and enabled on boot
  service:
    name: node_exporter
    state: started
    enabled: true