---
- name: Play 1 - replace SSL certificate for Jenkins
  hosts: jenkins        # ansible -i ~/ansible/inventory.ini jenkins -m ping
  become: true
  tasks:
    - name: Copy renewed SSL cert with appropriate permissions (docker-compose)
      copy:
        src: ~/ansible/fetched/certbot/int.leakespeake.com.pem
        dest: /home/ubuntu/docker-compose/jenkins/ssl/

    - name: Copy renewed SSL cert with appropriate permissions (host vm docker volume)
      copy:
        src: ~/ansible/fetched/certbot/int.leakespeake.com.pem
        dest: /var/lib/docker/volumes/jenkins_jenkins-haproxy-ssl/_data    

    - name: Reload reverse proxy for Jenkins
      shell: |
        docker stop cicd-haproxy
        docker rm cicd-haproxy
        docker-compose up -d
      args:
        chdir: /home/ubuntu/docker-compose/jenkins
        executable: /bin/bash

- name: Play 2 - replace SSL certificate for Prometheus
  hosts: localhost      # ansible localhost -m ping -vvv
  connection: local
  tasks:  
    - name: Find renewed SSL certs
      find:
        paths: ~/ansible/fetched/certbot/
        patterns: 'fullchain*,privkey*'
      register: files_to_copy

    - name: Remove old Prometheus SSL certs
      shell: rm -f ~/ansible/roles/cloudalchemy.prometheus/files/*.pem
      args:
        executable: /bin/bash       

    # .pem file names increment at each renewal - hardcoded within /files/webconfig.yml and tasks/install.yml
    # these numerical values are incremented automatically via certbot-increment-pem.yml
    - name: Copy renewed SSL certs to role files/ directory for upload
      copy:
        src: "{{ item.path }}"
        dest: ~/ansible/roles/cloudalchemy.prometheus/files
        force: false
      with_items: "{{ files_to_copy.files }}"

    - name: Run the Prometheus playbook to upload new SSL certs
      shell:
        ansible-playbook -i ~/ansible/inventory.ini prometheus-stack.yml
      args:
        executable: /bin/bash
        chdir: ~/ansible

- name: Play 3 - replace SSL certificate for PHP IPAM
  hosts: php_ipam       # ansible -i ~/ansible/inventory.ini php_ipam -m ping
  become: true
  tasks:  
    - name: Copy renewed SSL cert with appropriate permissions (docker-compose)
      copy:
        src: ~/ansible/fetched/certbot/int.leakespeake.com.pem
        dest: /home/ubuntu/docker-compose/php-ipam

    - name: Copy renewed SSL cert with appropriate permissions (host vm docker volume)
      copy:
        src: ~/ansible/fetched/certbot/int.leakespeake.com.pem
        dest: /var/lib/docker/volumes/php-ipam_phpipam-haproxy-ssl/_data         

    - name: Reload reverse proxy for PHP-IPAM
      shell: |
        docker stop php-ipam_phpipam-haproxy_1
        docker rm php-ipam_phpipam-haproxy_1
        docker-compose up -d
      args:
        chdir: /home/ubuntu/docker-compose/php-ipam
        executable: /bin/bash

- name: Play 4 - replace SSL certificate for Vault
  hosts: vault          # ansible -i ~/ansible/inventory.ini vault -m ping
  become: true
  tasks:  
    - name: Remove old Vault SSL certs
      shell: rm -f /home/ubuntu/docker-compose/vault/ssl/*.pem
      args:
        executable: /bin/bash       

    # .pem file names increment at each renewal - hardcoded within ~/docker-compose/vault/config/vault-config.json
    # these numerical values are incremented automatically via certbot-increment-pem.yml
    - name: Copy renewed SSL cert with appropriate permissions (docker-compose)
      copy:
        src: ~/ansible/fetched/certbot/
        dest: /home/ubuntu/docker-compose/vault/ssl 

    - name: Restart Vault container to load certs - requires manual unseal op
      shell: |
        docker stop vault-server
        docker rm vault-server
        docker-compose up -d
      args:
        chdir: /home/ubuntu/docker-compose/vault
        executable: /bin/bash