---
- name: LVM management with disk partitioning, formatting and mounting
  hosts: ubuntu_20_04_prd
  become: yes
  become_method: sudo

  vars:
    parted:
    # creates /dev/sdb1 partition
      - device: /dev/sdb
        number: 1
        label: gpt
        flags: [ lvm ]
        state: present
    lvg:
    # add /dev/sdb1 partition to our volume group, in addition to /dev/sda3
      - vg: ubuntu-vg
        pvs: "/dev/sda3,/dev/sdb1"
    lvol:
    # create a new logical volume 'lv-data' from our volume group
      - vg: ubuntu-vg
        lv: lv-data
        shrink: no
        size: 100%FREE
    filesystem:
    # format the logical volume with the ext4 filesystem
      - fstype: ext4
        dev: /dev/ubuntu-vg/lv-data
    mount:
    # create a persistent mount in /etc/fstab
      - path: /var
        src: /dev/ubuntu-vg/lv-data
        fstype: ext4
        opts: defaults
    
  roles:
    - disk-config