---
- name: LVM management with disk partitioning, formatting and mounting
  hosts: ubuntu_20_04_prd
  become: yes
  become_method: sudo

  vars:
    parted:
    # creates /dev/sdb1 partition from /dev/sdb block device
      - device: /dev/sdb
        number: 1
        label: gpt
        flags: [ lvm ]
        state: present
    lvg:
    # add /dev/sdb1 partition to our volume group - in addition to /dev/sda3
      - vg: ubuntu-vg
        pvs:
          - /dev/sda3
          - /dev/sdb1
    lvol:
    # extend existing logical volume 'ubuntu-lv' using the size of all remaining space in the volume group, then resize the filesystem
      - vg: ubuntu-vg
        lv: ubuntu-lv
        shrink: no
        size: 100%VG
        resizefs: true
    
  roles:
    - disk-config