---
- name: install and configure prometheus node exporter
  hosts: all  # amend ansible groups via inventory.ini for centralized node targeting (across playbooks)
  become: yes
  tasks:
    - name: use the node exporter role
      import_role:
        name: node-exporter
