---
- name: Deploy and configure a Prometheus stack
  hosts: all # amend ansible groups via inventory.ini for centralized node targeting (across playbooks)
  become: yes
  tasks:
    - name: Use Ansible Galaxy Prometheus role
      import_role:
        name: cloudalchemy.prometheus
      vars:
        prometheus_version: latest
        prometheus_storage_retention: "15d"
        prometheus_web_external_url: "http://{{ ansible_host }}:9090"

    - name: Use Ansible Galaxy Grafana role
      import_role:
        name: cloudalchemy.grafana
      vars:
        grafana_version: latest