---
- hosts: all # amend ansible groups via inventory.ini for centralized node targeting (across playbooks)
  become: true
  tasks:
- import_playbook: disk-config.yml
# CHECKS;
# df -h
# parted -l
# lsblk -x KNAME -o KNAME,SIZE,TRAN,SUBSYSTEMS,FSTYPE,UUID,LABEL,MODEL,SERIAL
# sudo pvs ; sudo vgs ; sudo lvs
# blkid
# cat /etc/fstab

- import_playbook: node-exporter.yml
# CHECKS;
# systemctl status node_exporter 
# curl http://localhost:9100/metrics

- import_playbook: vm-extra-config.yml
# CHECKS;
# cut -d: -f1 /etc/passwd
# ssh ubuntu_extra_user@server-01.example.com
# cat ~/.bashrc
# source ~/.bashrc
# history
# path

- import_playbook: vm-extra-security.yml
# CHECKS;
# crontab -l
# cat /etc/pam.d/common-password
# sudo passwd ubuntu_extra_user
# sudo ufw status verbose
# ssh root@server-01.example.com
# sudo fail2ban-client status

- import_playbook: upgrade-ubuntu-server.yml