---
- name: Additional Ubuntu 22.04 configuration
  hosts: all  # amend ansible groups via inventory.ini for centralized node targeting (across playbooks)
  become: yes
  vars:
    ubuntu_username: ubuntu
    ubuntu_extra_user: nested

  tasks:
    # ADD 2ND USER - password hash generated via: mkpasswd --method=sha-512
    - name: Create secondary logon account
      user:
        name: "{{ ubuntu_extra_user }}"
        password: '$6$tp81zrQSQMgGTLiZ$piunb.oK8WOx5x08dPQ9kUVMKtdCuDDgEJYV78N/sT9dgtzM9R9kn/TI7Us6G562Zb78BeM1RMehutGpj9Q6A.'
        create_home: yes
        groups:
          - sudo
          - docker
        state: present

    # ADD EXISTING PUBLIC SSH KEY FOR 2ND USER - negates manual use of ssh-copy-id utility
    - name: Add public key to ~/.ssh/authorized_keys for secondary logon account
      authorized_key:
        user: "{{ ubuntu_extra_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible_id_rsa.pub') }}"

    # ADD DATE & TIME FOR COMMAND HISTORY
    - name: Add HISTTIMEFORMAT to ~/.bashrc
      lineinfile:
        path: "{{ item.path }}"
        insertafter: 'HISTCONTROL=ignoreboth'
        line: 'HISTTIMEFORMAT="%F %T "'
      with_items:
        - {path: "/home/{{ ubuntu_username }}/.bashrc"}
        - {path: "/home/{{ ubuntu_extra_user }}/.bashrc"}        

    # ADD ALIASES
    - name: Add favourite aliases to ~/.bashrc
      blockinfile:
        path: "{{ item.path }}"
        insertbefore: "# Alias definitions"
        block: |
          # Personal aliases
          alias update='sudo apt update && sudo apt -y upgrade'
          alias path='echo $PATH | tr ":" "\n" | nl'
          alias mount='mount |column -t'
          alias ls='ls -la'
          alias top='htop'
          alias df='pydf'
          alias du='ncdu'
          alias ss='ss -tulpn'
          alias hs='history | grep'
          alias myip='curl ipinfo.io/ip'
      with_items:
        - {path: "/home/{{ ubuntu_username }}/.bashrc"}
        - {path: "/home/{{ ubuntu_extra_user }}/.bashrc"}    

    - name: Insert empty line before ANSIBLE MANAGED BLOCK
      replace:
        path: "{{ item.path }}"
        regexp: "(?<=.\n)# BEGIN ANSIBLE MANAGED BLOCK$"
        replace: "\n# BEGIN ANSIBLE MANAGED BLOCK"   
      with_items:
        - {path: "/home/{{ ubuntu_username }}/.bashrc"}
        - {path: "/home/{{ ubuntu_extra_user }}/.bashrc"}            

    - name: Insert empty line after ANSIBLE MANAGED BLOCK
      replace:
        path: "{{ item.path }}"
        regexp: "(?<=.\n)# Alias definitions.$"
        replace: "\n# Alias definitions."    
      with_items:
        - {path: "/home/{{ ubuntu_username }}/.bashrc"}
        - {path: "/home/{{ ubuntu_extra_user }}/.bashrc"}            
        