---
- name: Configure block device partitions
  parted:
    device: '{{ item.device }}'
    align: '{{ item.align | default(omit) }}'
    flags: '{{ item.flags | default(omit) }}'
    label: '{{ item.label | default("gpt") }}'
    name: '{{ item.name | default(omit) }}'
    number: '{{ item.number | default(omit) }}'
    part_end: '{{ item.part_end | default(omit) }}'
    part_start: '{{ item.part_start | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    unit: '{{ item.unit | default(omit) }}'
  with_items: '{{ parted }}'

- name: Configure LVM volume groups
  lvg:
    vg: '{{ item.vg }}'
    force: '{{ item.force | default(omit) }}'
    pesize: '{{ item.pesize | default(omit) }}'
    pv_options: '{{ item.pv_options | default(omit) }}'
    pvs: '{{ item.pvs | default(omit) }}'
    pvresize: '{{ item.pvresize | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    vg_options: '{{ item.vg_options | default(omit) }}'
  with_items: '{{ lvg }}'

- name: Configure LVM logical volumes
  lvol:
    lv: '{{ item.lv }}'
    vg: '{{ item.vg }}'
    active: '{{ item.active | default(omit) }}'
    force: '{{ item.force | default(omit) }}'
    opts: '{{ item.opts | default(omit) }}'
    pvs: '{{ item.opts | default(omit) }}'
    resizefs: '{{ item.resizefs | default(omit) }}'
    shrink: '{{ item.shrink | default(omit) }}'
    size: '{{ item.size | default(omit) }}'
    snapshot: '{{ item.snapshot | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    thinpool: '{{ item.thinpool | default(omit) }}'
  with_items: '{{ lvol }}'

- name: Make a filesystem type
  filesystem:
    dev: '{{ item.dev }}'
    fstype: '{{ item.fstype }}'
    force: '{{ item.force | default(omit) }}'
    opts: '{{ item.opts | default(omit) }}'
    resizefs: '{{ item.resizefs | default(omit) }}'
  with_items: '{{ filesystem }}'  

- name: Control active and configured mount points
  mount:
    fstype: '{{ item.fstype }}'
    src: '{{ item.src }}'
    path: '{{ item.path }}'
    backup: '{{ item.backup | default(omit) }}'
    boot: '{{ item.boot | default(omit) }}'
    dump: '{{ item.dump | default(omit) }}'
    fstab: '{{ item.fstab | default(omit) }}'
    opts: '{{ item.opts  | default("defaults") }}'
    passno: '{{ item.passno | default(omit) }}'
    state: '{{ item.state  | default("mounted")  }}'
  with_items: '{{ mount }}'