---
# variables with low precedence - ansible will only use them if not defined elsewhere
node_exporter_version: 1.2.2
node_exporter_download_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
node_exporter_user: node-exporter
node_exporter_group: "{{ node_exporter_user }}"

# configuration flags to pass to node_exporter - see ExecStart in our Jinja2 systemd template
node_exporter_config_flags:
  'web.listen-address': '0.0.0.0:9100'
  'log.level': 'info'