---
- name: Configure Ubuntu - install essential packages
  hosts: wsl2
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Install favourite base packages with apt
      apt:
        name:
          - bashtop
          - htop
          - gzip
          - ncdu
          - pydf
          - net-tools
          - nmap
          - curl
          - openssh-server
    - name: Add Docker’s GPG key and set up stable repository
      shell:
        cmd: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - name: Install git and Docker
      apt:
        name:
          - git
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: latest
    - name: Add user to docker group
      user:
        name: "{{ ubuntu_username }}"
        group: docker