---
- hosts: windows
  connection: local
  tasks:
    - name: Install base essential packages with Chocolatey
      win_chocolatey:
        name:
        - vscode
        - git
        - docker-desktop
        - dropbox
        state: latest