---
- name: Configure Windows 10 for development
- hosts: windows
  connection: local
  tasks:
    - name: Install Chocolatey
      win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Install base essential packages with Chocolatey
      win_chocolatey:
        name:
        - vscode
        - git
        - docker-desktop
        - notepadplusplus
        - firefox
        - googlechrome
        - 7zip
        - putty
        - mremoteng
        state: latest

    - name: Enable file extension
      win_shell: |
        Push-Location
        Set-Location HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        Set-ItemProperty . HideFileExt "0"
        Pop-Location
        Stop-Process -processName: Explorer -force

    - name: Show hidden files
      win_shell: |
        $value = -not $Off.IsPresent
        Set-ItemProperty -Path HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced `
        -Name Hidden -Value 'On' -type DWORD
        
        $shell = New-Object -ComObject Shell.Application
        $shell.Windows() |
            Where-Object { $_.document.url -eq $null } |
            ForEach-Object { $_.Refresh() }