---
- name: Configure Windows 10 for development
  hosts: windows
  tasks:
    - name: Install favourite base packages with Chocolatey
      win_chocolatey:
        name:
        - vscode
        - vscode-python
        - vscode-ansible
        - vscode-docker
        - git
        - terraform
        - packer
        - docker-desktop
        - notepadplusplus
        - firefox
        - googlechrome
        - 7zip
        - putty
        - mremoteng
        - nmap
        - filezilla
        - python
        - passwordsafe
        state: latest
    - name: Show file extensions
      win_shell: |
        Push-Location
        Set-Location HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        Set-ItemProperty . HideFileExt "0"
        Pop-Location
        Stop-Process -processName: Explorer -force
    - name: Show hidden files
      win_shell: |
        $value = -not $Off.IsPresent
        Set-ItemProperty -Path HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced `
        -Name Hidden -Value 'On' -type DWORD
        
        $shell = New-Object -ComObject Shell.Application
        $shell.Windows() |
            Where-Object { $_.document.url -eq $null } |
            ForEach-Object { $_.Refresh() }