---
- name: Configure Ubuntu - configuration imports and file amendments
  hosts: wsl2
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Add favourite aliases to ~/.bashrc
      blockinfile:
        dest: /etc/hosts
        block: |
          alias update='sudo apt update && sudo apt -y upgrade'
          alias path='echo $PATH | tr ":" "\n" | nl'
          alias mount='mount |column -t'
