---
- name: Configure Ubuntu - configuration imports and file amendments
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: Add favourite aliases to ~/.bashrc
      blockinfile:
        path: "/home/{{ ubuntu_username }}/.bashrc"
        insertbefore: "# Alias definitions"
        block: |
          # Personal aliases
          alias update='sudo apt update && sudo apt -y upgrade'
          alias path='echo $PATH | tr ":" "\n" | nl'
          alias mount='mount |column -t'
          alias ls='ls -la'
          alias top='bashtop'
          alias df='pydf'
          alias du='ncdu'
          alias netstat='netstat -tulpn'
          alias hs='history | grep'
          alias myip='curl ipinfo.io/ip'
    - name: Insert an empty line before ANSIBLE MANAGED BLOCK
      replace:
        path: "/home/{{ ubuntu_username }}/.bashrc"
        regexp: "(?<=.\n)# BEGIN ANSIBLE MANAGED BLOCK$"
        replace: "\n# BEGIN ANSIBLE MANAGED BLOCK"
    - name: Insert an empty line after ANSIBLE MANAGED BLOCK
      replace:
        path: "/home/{{ ubuntu_username }}/.bashrc"
        regexp: "(?<=.\n)# Alias definitions.$"
        replace: "\n# Alias definitions."
